### PR TITLE
feat: optionally allow attaching a waf policy to cdn

### PR DESCRIPTION
**Pull request by jamesla**
This PR exposes the webacl param on the cloudfront distribution allowing you to pass a waf acl in to do things like restrict traffic from certain ip's or perform application security scanning at the edge

### CODE REVIEW

**Comment by jamesla** [comment]
bump

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
This is the PR I needed!

**Comment by ofhouse** [comment]
Thanks for the PR & sorry for the delay here.
Will try to get it merged by end of this week & release a new version from it 👍

**Comment by ofhouse** [comment]
This has been released in [`v0.11.0`](https://github.com/milliHQ/terraform-aws-next-js/releases/tag/v0.11.0).

**Pull request merged**
